version: "3.7"
services:
  app:
    build:
      args:
        user: eugene
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: currencymonitor
    container_name: currencymonitor-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - currencymonitor
    ports:
      - 6001:6001
  nginx:
    image: nginx:alpine
    container_name: currencymonitor-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    networks:
      - currencymonitor

networks:
  currencymonitor:
    driver: bridge
